Added-content
andersonlebon/Survery-form-Review pull request #1
Opened 2021-06-02 10:13 UTC by andersonlebon

## Here are what was done to give the on project meaningful content:

- [ ]  Add significant information in the HTML and CSS files
- [ ]  Modified the link demo in the README file to a valid link

2021-06-02 10:34 UTC, andersonlebon reviewed
These are changes that would  be better to change them:

- [x]  Make sure all linter's  errors disappear ;
- [ ] I think it would be better to use semantic tags,
- [ ]  And Applied HTML & CSS best practices.

2021-06-02 21:28 UTC, christianotieno requested changes
Hi @andersonlebon, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>


 ## Required Changes ♻️
_Check the comments under the review._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-06-02 21:28 UTC, christianotieno commented on style.css
> +}
## Changes required in review:
- This was a good review, You did try to capture the most aspect of the code in the review. There was also a great effort in trying to point out wherein the code changes got require. Good job.
- [ ] I would encourage the use of a couple of emojis and/or gifs in all of your reviews. They make the code review more human-friendly 👽🤖
- [ ] I think you also needed to have used the [GitHub inline comments feature](/microverse/guides/tse/code_review/code_review_guidelines_2_0/-/blob/master/ADD_LINK_TO_VIDEO_OR_ARTCILE) at least once to leave review comments. That way the code review would have been complete.
- [ ] I think your reviews lacked the `why` explanations on the necessity of the changes. I'd encourage you to always try and includes an explanation, a "why", for each requested change. Thereby your reviews don't come off as commanding but rather complete and deliberate. 
- [ ] Kindly try and make these changes and then resubmit for another re-review. Thank you!

2021-06-03 09:44 UTC, andersonlebon reviewed
> Well done :clap: However these are changes that would be better to make:
## Required Changes
 
- [ ]  As programmers, you will be part of a team. Agreeing on a set of coding standards is key to create quality code as a team, and linters will facilitate this task. So I think it would be better :thumbsup:  to make sure all linter's errors disappear ;
- [ ]  I think it would be better to use semantic HTML tags, because a consistent, clean, and tidy HTML code makes it easier for others to read and understand your code.

2021-06-03 12:10 UTC, Spayco approved these changes
Hi @andersonlebon, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-06-03 12:10 UTC, Spayco commented on index.html
> +
please note here: I know you described the reason in the summary, but it would be better to have them all in one please, or at least inform the reader where the reason is

2021-06-03 13:17 UTC, merged